#!/usr/bin/env ruby

require 'shellwords'

command =<<-eos
  tell application "iTerm"
    tell the first terminal
      # launch session "RSpec"
      tell the current session
        write text "bundle exec rspec #{ARGV.join(' ')}"
      end tell
    end tell
  end tell
eos

if File.exist?(ENV['HOME'] + '/.rvmrc')
  exec( """
        echo \"  command: bundle exec rspec #{ARGV.join(' ')} --color\"
        echo \"-------------------------------------------------------------\"
        osascript -e '#{command}'
        """ )
elsif File.exist?(ENV['HOME'] + '/.rbenv')
  exec( """
        echo \"  command: ~/.rbenv/shims/bundle exec rspec #{ARGV.join(' ')} --color\"
        echo \"-------------------------------------------------------------\"
        osascript -e '#{command}'
        """ )
else
  STDERR.puts("'.rvm' or '.rbenv' directories not found in your home path")
  exit(-1)
end

puts "Could not find any .rvmrc or .rbenv above #{file}"

exec( """
      echo \"command: bundle exec rspec #{file}\"
      bundle exec rspec #{file} --color
      """ )

exit(-1)
