#!/usr/bin/env ruby

require 'shellwords'

if File.exist?(ENV['HOME'] + '/.rvmrc')
  exec( """
        echo \"  command: bundle exec ruby #{ARGV.join(' ')}\"
        echo \"------------------------------------------------------------------------------\"
        bundle exec ruby #{ARGV.join(' ')}
        """ )
elsif File.exist?(ENV['HOME'] + '/.rbenv')
  exec( """
        echo \"  command: ~/.rbenv/shims/bundle exec ruby #{ARGV.join(' ')}\"
        echo \"------------------------------------------------------------------------------\"
        ~/.rbenv/shims/bundle exec ruby #{ARGV.join(' ')}
        """ )
else
  STDERR.puts("'.rvm' or '.rbenv' directories not found in your home path")
  exit(-1)
end

puts "Could not find any .rvmrc or .rbenv above #{ARGV.join(' ')}"

exec( """
      echo \"command: ruby -Ilib:bin:test:. #{ARGV.join(' ')}\"
      ruby -I.:lib:test #{ARGV.join(' ')}
      """ )

exit -1