#!/usr/bin/env ruby

file = File.expand_path(ARGV[0] || (STDERR.puts('you must specify a ruby file'); exit(-1)))
dir = File.dirname file
while dir.size > 1
  if File.exist?(dir + '/.rvmrc')
    exec( """
          source \"$HOME/.rvm/scripts/rvm\"
          echo \"directory: #{dir}\"
          echo \"  command: ruby #{file}\"
          echo \"-------------------------------------------------------------\"
          cd #{dir}
          ruby #{file}
          """ )
  elsif File.exist?(dir + '/.rbenv')
    exec( """
          echo \"directory: #{dir}\"
          echo \"  command: /usr/local/bin/rbenv ruby #{file}\"
          echo \"-------------------------------------------------------------\"
          cd #{dir}
          /usr/local/bin/rbenv ruby #{file}
          """ )
  else
    dir = dir.sub(/\/[^\/]*$/, '')
  end
end

puts "Could not find any .rvmrc or .rbenv above #{file}"

exec( """
      echo \"command: ruby #{file}\"
      ruby #{file}
      """ )

exit -1