#!/usr/bin/env ruby

file = File.expand_path(ARGV[0] || (STDERR.puts('you must specify a ruby file'); exit(-1)))
dir = File.dirname file
puts dir
while dir.size > 1

  if File.exist?(dir + '/.rvmrc')
    exec( """
          source \"$HOME/.rvm/scripts/rvm\"
          echo \"directory: #{dir}\"
          echo \"  command: bundle exec spec #{file} --color --drb\"
          echo \"-------------------------------------------------------------\"
          cd #{dir}
          bundle exec spec #{file} --color --drb
          """ )
  elsif File.exist?(dir + '/.rbenv')
    exec( """
          echo \"directory: #{dir}\"
          echo \"  command: /usr/local/bin/rbenv bundle exec spec #{file} --color --drb\"
          echo \"-------------------------------------------------------------\"
          cd #{dir}
          /usr/local/bin/rbenv spec #{file} --color --drb
          """ )
  else
    dir = dir.sub(/\/[^\/]*$/, '')
  end
end

puts "Could not find any .rvmrc or .rbenv above #{file}"

exec( """
      echo \"command: bundle exec spec #{file}\"
      bundle exec spec #{file} --color --drb
      """ )

exit(-1)